### ISSUE TITLE
links in colaboratory text cells

### ISSUE THREAD

**Issue by samskillman** [jupyter/colaboratory#72] opened 2014-08-06 19:10 UTC
If you put an http link in the colaboratory notebook as a text cell, it will open within the same app window rather than a new chrome tab.

**Comment by dominichosler** [comment] 2017-02-02 14:09
I think this is a duplicate of issue #102 which has already had activity on it.

**Comment by rgbkrk** [comment] 2017-10-29 21:14
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.

**Closed by rgbkrk** 2017-10-29 21:14 UTC
